/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdminRole;

import Business.Supplier;
import Business.SupplierDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fjx19
 */
public class SupplierMngJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    SupplierDirectory supplierDirectory;
    /**
     * Creates new form SupplierMngJPanel
     */


    SupplierMngJPanel(JPanel userProcessContainer, SupplierDirectory supplierDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.supplierDirectory = supplierDirectory;
        populateTable();
    }
    void populateTable() {
        int rowCount = CatalogTbl.getRowCount();
        DefaultTableModel dtm = (DefaultTableModel)CatalogTbl.getModel();
        for(int i = rowCount-1 ; i>=0 ; i--){
            dtm.removeRow(i);
        }       
        for(Supplier supplier : supplierDirectory.getSupplierDirectory())
        {   
            Object row[] = new Object[1];
            row[0] = supplier;
            dtm.addRow(row);
           }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        CatalogTbl = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();
        addSupplierBtn = new javax.swing.JButton();
        deleteSupplierBtn = new javax.swing.JButton();
        viewSupplierBtn = new javax.swing.JButton();

        CatalogTbl.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        CatalogTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Supplier Name"
            }
        ));
        jScrollPane1.setViewportView(CatalogTbl);

        backBtn.setText("<<Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        addSupplierBtn.setText("Add Supplier");
        addSupplierBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSupplierBtnActionPerformed(evt);
            }
        });

        deleteSupplierBtn.setText("delete Supplier");
        deleteSupplierBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteSupplierBtnActionPerformed(evt);
            }
        });

        viewSupplierBtn.setText("View Supplier");
        viewSupplierBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSupplierBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(viewSupplierBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteSupplierBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addSupplierBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(219, 219, 219)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(backBtn))))
                .addContainerGap(229, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(backBtn)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addSupplierBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewSupplierBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteSupplierBtn)
                .addContainerGap(229, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void addSupplierBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSupplierBtnActionPerformed
        // TODO add your handling code here:
        AddSupplierJPanel panel = new AddSupplierJPanel(userProcessContainer, supplierDirectory);
        userProcessContainer.add("AddSupplierJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_addSupplierBtnActionPerformed

    private void viewSupplierBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSupplierBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = CatalogTbl.getSelectedRow();
        if(selectedRow<0)
             JOptionPane.showMessageDialog(null, "Please select any row", "warning", JOptionPane.WARNING_MESSAGE);
        else{
            Supplier supplier = (Supplier) CatalogTbl.getValueAt(selectedRow, 0);
            ViewSupplierJPanel panel = new ViewSupplierJPanel(userProcessContainer, supplier);
            userProcessContainer.add("ViewSupplierJPanel", panel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_viewSupplierBtnActionPerformed

    private void deleteSupplierBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSupplierBtnActionPerformed
        // TODO add your handling code here:
        int selectedrow = CatalogTbl.getSelectedRow();
        
        if(selectedrow >=0)
        {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null, "Are you sure to delete?", "warning", dialogButton);
            if(dialogResult == JOptionPane.YES_OPTION){
                Supplier supplier = (Supplier) CatalogTbl.getValueAt(selectedrow, 0);
                supplierDirectory.deleteSupplier(supplier);
                JOptionPane.showMessageDialog(null, "Supplier has been deleted");
                populateTable();
            }

            
        }
        else
            JOptionPane.showMessageDialog(null, "Please select any row", "warning", JOptionPane.WARNING_MESSAGE);
                                           
    }//GEN-LAST:event_deleteSupplierBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable CatalogTbl;
    private javax.swing.JButton addSupplierBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton backBtn1;
    private javax.swing.JButton deleteSupplierBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton viewSupplierBtn;
    // End of variables declaration//GEN-END:variables
}
