/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacePac;
import java.io.*;
import javax.swing.*;
import javax.imageio.*;
import java.util.regex.Pattern;
import java.util.regex.Matcher;
import java.awt.*;
/**
 *
 * @author fjx19
 */
import javax.swing.JOptionPane;
import people.Resume;
import people.ResumeHistory;


public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    private ResumeHistory rh;
    private Resume r;
    private String gender;
    private String path;
    private String workexperience;
    private String status;
    private String java = "";
    private String cplusplus = "";
    private String csharp = "";
    private String vb = "";
    private boolean valid = true;
    
    public CreateJPanel(ResumeHistory rh) {
        initComponents();
        this.rh=rh;
    }
    public boolean isNumeric(String str){ 
       Pattern pattern = Pattern.compile("[0-9]*"); 
       Matcher isNum = pattern.matcher(str);
       if( !isNum.matches() ){
       return false; 
       } 
       return true; 
    }
    
    private void validateInput(){
        if(!isNumeric(ageTxt.getText())){
            JOptionPane.showMessageDialog(null,"Please input correct age");
            valid = false;
        }
        else if(!isNumeric(telTxt.getText())){
            JOptionPane.showMessageDialog(null,"Please input correct Phone number");
            valid = false;
        }
        else if(path == null){
            JOptionPane.showMessageDialog(null,"Please select a photo");
            valid = false;
        }
        else
            valid = true;
    }
    
    private void setValueOfResume(){
        String firstname = fistnameTxt.getText();
        String lastname = lastnameTxt.getText();
        String dateofbirth = dobTxt.getText();
        String age = ageTxt.getText();
        String Tel = telTxt.getText();
        String email = emailTxt.getText();
        String streetln1 = st1Txt.getText();
        String streetln2 = st2Txt.getText();
        String city = cityTxt.getText();
        String country = countryTxt.getText();
        String affiliation =affiliationTxt.getText();
        String major = majorTxt.getText();
        String career = careerTxtarea.getText();
        String degree1 = degree1Txt.getText();
        String degree1start = start1Txt.getText();
        String degree1end = end1Txt.getText();
        String degree2 = degree2Txt.getText();
        String degree2start = start2Txt.getText();
        String degree2end = end2Txt.getText();
        
        r=rh.addResume();
        r.setFirstname(firstname);
        r.setLastname(lastname);
        r.setDateofbirth(dateofbirth);
        r.setAge(age);
        r.setTel(Tel);
        r.setEmail(email);
        r.setStreetln1(streetln1);
        r.setStreetln2(streetln2);
        r.setCity(city);
        r.setCountry(country);
        r.setAffiliation(affiliation);
        r.setMajor(major);
        r.setCareer(career);
        r.setDegree1(degree1);
        r.setDegree1start(degree1start);
        r.setDegree1end(degree1end);
        r.setDegree2(degree2);
        r.setDegree2start(degree2start);
        r.setDegree2end(degree2end);
        r.setSex(gender);
        r.setPath(path);
        r.setWork(workexperience);
        r.setStatus(status);
        r.setJava(java);
        r.setCplusplus(cplusplus);
        r.setCsharp(csharp);
        r.setVb(vb);
        
        JOptionPane.showMessageDialog(null,"Added Successfully");
        
        fistnameTxt.setText("");
        lastnameTxt.setText("");
        dobTxt.setText("");
        ageTxt.setText("");
        telTxt.setText("");
        emailTxt.setText("");
        st1Txt.setText("");
        st2Txt.setText("");
        cityTxt.setText("");
        countryTxt.setText("");
        affiliationTxt.setText("");
        majorTxt.setText("");
        careerTxtarea.setText("");
        degree1Txt.setText("");
        start1Txt.setText("");
        end1Txt.setText("");
        degree2Txt.setText("");
        start2Txt.setText("");
        end2Txt.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        fistnameTxt = new javax.swing.JTextField();
        lastnameTxt = new javax.swing.JTextField();
        dobTxt = new javax.swing.JTextField();
        ageTxt = new javax.swing.JTextField();
        telTxt = new javax.swing.JTextField();
        emailTxt = new javax.swing.JTextField();
        st1Txt = new javax.swing.JTextField();
        st2Txt = new javax.swing.JTextField();
        cityTxt = new javax.swing.JTextField();
        countryTxt = new javax.swing.JTextField();
        affiliationTxt = new javax.swing.JTextField();
        majorTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        careerTxtarea = new javax.swing.JTextArea();
        degree1Txt = new javax.swing.JTextField();
        start1Txt = new javax.swing.JTextField();
        end1Txt = new javax.swing.JTextField();
        degree2Txt = new javax.swing.JTextField();
        start2Txt = new javax.swing.JTextField();
        end2Txt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        photoLab = new javax.swing.JLabel();
        chooseBtn = new javax.swing.JButton();
        maleRBtn = new javax.swing.JRadioButton();
        femaleRBtn = new javax.swing.JRadioButton();
        jLabel23 = new javax.swing.JLabel();
        workYesRBtn = new javax.swing.JRadioButton();
        workNoRBtn = new javax.swing.JRadioButton();
        jLabel24 = new javax.swing.JLabel();
        citizenRBtn = new javax.swing.JRadioButton();
        internationalRBtn = new javax.swing.JRadioButton();
        jLabel25 = new javax.swing.JLabel();
        cplusplusCBox = new javax.swing.JCheckBox();
        csharpCBox = new javax.swing.JCheckBox();
        vbCBox = new javax.swing.JCheckBox();
        javaCBox = new javax.swing.JCheckBox();

        jLabel1.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel1.setText("Create");

        jLabel2.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        jLabel2.setText("First Name:");

        jLabel3.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        jLabel3.setText("Last Name:");

        jLabel4.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        jLabel4.setText("Address:");

        jLabel5.setFont(new java.awt.Font("宋体", 2, 12)); // NOI18N
        jLabel5.setText("Streetline1:");

        jLabel6.setFont(new java.awt.Font("宋体", 2, 12)); // NOI18N
        jLabel6.setText("Streetline2:");

        jLabel7.setFont(new java.awt.Font("宋体", 2, 12)); // NOI18N
        jLabel7.setText("City:");

        jLabel8.setFont(new java.awt.Font("宋体", 2, 12)); // NOI18N
        jLabel8.setText("Country:");

        jLabel9.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        jLabel9.setText("Affiliation:");

        jLabel10.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        jLabel10.setText("Date of Birth:");

        jLabel11.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        jLabel11.setText("Age:");

        jLabel12.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        jLabel12.setText("Telephone:");

        jLabel13.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        jLabel13.setText("E-mail:");

        jLabel14.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        jLabel14.setText("Major:");

        jLabel15.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        jLabel15.setText("Career:");

        jLabel16.setFont(new java.awt.Font("宋体", 2, 12)); // NOI18N
        jLabel16.setText("End Time:");

        jLabel17.setFont(new java.awt.Font("宋体", 2, 12)); // NOI18N
        jLabel17.setText("Start Time:");

        jLabel19.setFont(new java.awt.Font("宋体", 2, 12)); // NOI18N
        jLabel19.setText("Degree1:");

        jLabel20.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        jLabel20.setText("Degree：");

        jLabel18.setFont(new java.awt.Font("宋体", 2, 12)); // NOI18N
        jLabel18.setText("Start Time:");

        jLabel21.setFont(new java.awt.Font("宋体", 2, 12)); // NOI18N
        jLabel21.setText("End Time:");

        jLabel22.setFont(new java.awt.Font("宋体", 2, 12)); // NOI18N
        jLabel22.setText("Degree2:");

        dobTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobTxtActionPerformed(evt);
            }
        });

        telTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telTxtActionPerformed(evt);
            }
        });

        emailTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTxtActionPerformed(evt);
            }
        });

        careerTxtarea.setColumns(20);
        careerTxtarea.setRows(5);
        jScrollPane1.setViewportView(careerTxtarea);

        jButton1.setText("Create");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        chooseBtn.setText("Choose photo");
        chooseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseBtnActionPerformed(evt);
            }
        });

        maleRBtn.setText("male");
        maleRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleRBtnActionPerformed(evt);
            }
        });

        femaleRBtn.setText("Female");
        femaleRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleRBtnActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        jLabel23.setText("Work Experience?");

        workYesRBtn.setText("Yes");
        workYesRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workYesRBtnActionPerformed(evt);
            }
        });

        workNoRBtn.setText("No");
        workNoRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workNoRBtnActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        jLabel24.setText("Status：");

        citizenRBtn.setText("Citizen");
        citizenRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                citizenRBtnActionPerformed(evt);
            }
        });

        internationalRBtn.setText("International");
        internationalRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                internationalRBtnActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        jLabel25.setText("Programming Skills:");

        cplusplusCBox.setText("C++");
        cplusplusCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cplusplusCBoxActionPerformed(evt);
            }
        });

        csharpCBox.setText("C#");
        csharpCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                csharpCBoxActionPerformed(evt);
            }
        });

        vbCBox.setText("VB");
        vbCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vbCBoxActionPerformed(evt);
            }
        });

        javaCBox.setText("java");
        javaCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                javaCBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(18, 18, 18)
                                .addComponent(workYesRBtn)
                                .addGap(38, 38, 38)
                                .addComponent(workNoRBtn))
                            .addComponent(jLabel25)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(javaCBox)
                                .addGap(18, 18, 18)
                                .addComponent(cplusplusCBox)
                                .addGap(18, 18, 18)
                                .addComponent(csharpCBox)
                                .addGap(18, 18, 18)
                                .addComponent(vbCBox)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(st1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(st2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel20)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(degree1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(affiliationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(majorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabel22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(degree2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(153, 153, 153)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(countryTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel21)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel17)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(start1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(32, 32, 32)
                                                    .addComponent(jLabel16)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel18)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(start2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(end1Txt)
                                            .addComponent(end2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(jButton1)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(citizenRBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(internationalRBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fistnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dobTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel1)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel13))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(telTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(maleRBtn)
                                .addGap(18, 18, 18)
                                .addComponent(femaleRBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lastnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ageTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chooseBtn)
                            .addComponent(photoLab, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(fistnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lastnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(maleRBtn)
                            .addComponent(femaleRBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(dobTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(photoLab, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(ageTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(citizenRBtn)
                            .addComponent(internationalRBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(telTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(chooseBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(st1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(st2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(cityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(countryTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(affiliationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(majorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cplusplusCBox)
                    .addComponent(csharpCBox)
                    .addComponent(vbCBox)
                    .addComponent(javaCBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(workYesRBtn)
                    .addComponent(workNoRBtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(degree1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16)
                    .addComponent(start1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(end1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(degree2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel21)
                    .addComponent(start2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(end2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(94, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dobTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dobTxtActionPerformed

    private void telTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telTxtActionPerformed

    private void emailTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTxtActionPerformed
        // TODO add your handling code here: 
    }//GEN-LAST:event_emailTxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //导入数据到resume
        validateInput();
        if(valid){
           setValueOfResume();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void chooseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseBtnActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChoose=new JFileChooser();
        fileChoose.showOpenDialog(null);
        File file=fileChoose.getSelectedFile();
        path=file.getPath();
        
        
      
        
        ImageIcon icon=new ImageIcon(path);
        photoLab.setIcon(icon);
        Image in = null;
        try{
            in =javax.imageio.ImageIO.read(new File(path));
        }catch(Exception e){
        }
        in = in.getScaledInstance( 128, 128, Image.SCALE_DEFAULT);
        photoLab.setIcon(new ImageIcon(in)) ;
//        r.setPath(path);
        
        
        
        
    }//GEN-LAST:event_chooseBtnActionPerformed

    private void maleRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleRBtnActionPerformed
        // TODO add your handling code here:
        if(maleRBtn.isSelected()){
            gender = "male";
            femaleRBtn.setSelected(false);
        }
        
    }//GEN-LAST:event_maleRBtnActionPerformed

    private void femaleRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleRBtnActionPerformed
        // TODO add your handling code here:
        if(femaleRBtn.isSelected()){
            gender = "female";
            maleRBtn.setSelected(false);
        }
    }//GEN-LAST:event_femaleRBtnActionPerformed

    private void workYesRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workYesRBtnActionPerformed
        // TODO add your handling code here:
        if(workYesRBtn.isSelected()){
            workexperience = "Yes";
            workNoRBtn.setSelected(false);
            careerTxtarea.setEnabled(true);
            
        }
    }//GEN-LAST:event_workYesRBtnActionPerformed

    private void workNoRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workNoRBtnActionPerformed
        // TODO add your handling code here:
        if(workNoRBtn.isSelected()){
            workexperience = "no";
            workYesRBtn.setSelected(false);
            careerTxtarea.setEnabled(false);
            
        }
    }//GEN-LAST:event_workNoRBtnActionPerformed

    private void citizenRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_citizenRBtnActionPerformed
        // TODO add your handling code here:
        if(citizenRBtn.isSelected()){
            status = "Citizen";
            internationalRBtn.setSelected(false);
        }
    }//GEN-LAST:event_citizenRBtnActionPerformed

    private void internationalRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_internationalRBtnActionPerformed
        // TODO add your handling code here:
         if(internationalRBtn.isSelected()){
            status = "Citizen";
            citizenRBtn.setSelected(false);
         }
    }//GEN-LAST:event_internationalRBtnActionPerformed

    private void javaCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_javaCBoxActionPerformed
        // TODO add your handling code here:
        if(javaCBox.isSelected()){
            java = "java; ";
            
        }
        else
            java = " ";
    }//GEN-LAST:event_javaCBoxActionPerformed

    private void cplusplusCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cplusplusCBoxActionPerformed
        // TODO add your handling code here:
        if(cplusplusCBox.isSelected()){
            cplusplus = "C++; ";
        }
        else
            cplusplus = " ";
    }//GEN-LAST:event_cplusplusCBoxActionPerformed

    private void csharpCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csharpCBoxActionPerformed
        // TODO add your handling code here:
        if(csharpCBox.isSelected()){
            csharp = "C#; ";
        }
        else 
            csharp = " ";
    }//GEN-LAST:event_csharpCBoxActionPerformed

    private void vbCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vbCBoxActionPerformed
        // TODO add your handling code here:
        if(vbCBox.isSelected()){
            vb = "VB; ";
        }
        else
            vb = " ";
    }//GEN-LAST:event_vbCBoxActionPerformed
   
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField affiliationTxt;
    private javax.swing.JTextField ageTxt;
    private javax.swing.JTextArea careerTxtarea;
    private javax.swing.JButton chooseBtn;
    private javax.swing.JRadioButton citizenRBtn;
    private javax.swing.JTextField cityTxt;
    private javax.swing.JTextField countryTxt;
    private javax.swing.JCheckBox cplusplusCBox;
    private javax.swing.JCheckBox csharpCBox;
    private javax.swing.JTextField degree1Txt;
    private javax.swing.JTextField degree2Txt;
    private javax.swing.JTextField dobTxt;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JTextField end1Txt;
    private javax.swing.JTextField end2Txt;
    private javax.swing.JRadioButton femaleRBtn;
    private javax.swing.JTextField fistnameTxt;
    private javax.swing.JRadioButton internationalRBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox javaCBox;
    private javax.swing.JTextField lastnameTxt;
    private javax.swing.JTextField majorTxt;
    private javax.swing.JRadioButton maleRBtn;
    private javax.swing.JLabel photoLab;
    private javax.swing.JTextField st1Txt;
    private javax.swing.JTextField st2Txt;
    private javax.swing.JTextField start1Txt;
    private javax.swing.JTextField start2Txt;
    private javax.swing.JTextField telTxt;
    private javax.swing.JCheckBox vbCBox;
    private javax.swing.JRadioButton workNoRBtn;
    private javax.swing.JRadioButton workYesRBtn;
    // End of variables declaration//GEN-END:variables
}
