/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface;

import business.Product;
import business.ProductDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author fjx19
 */
public class ProductMngWorkAreaJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private ProductDirectory productDirectory;


    /**
     * Creates new form ProductMngWorkArea
     */

    ProductMngWorkAreaJPanel(JPanel userProcessContainer, ProductDirectory productDirectory) {
       initComponents();
       this.userProcessContainer = userProcessContainer;
       this.productDirectory = productDirectory;

       

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        computerBtn = new javax.swing.JButton();
        printerBtn = new javax.swing.JButton();
        hardwareBtn = new javax.swing.JButton();
        softwareBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        vendorIDTxt = new javax.swing.JTextField();

        computerBtn.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        computerBtn.setText("Computer Catalog");
        computerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computerBtnActionPerformed(evt);
            }
        });

        printerBtn.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        printerBtn.setText("Printer Catalog");
        printerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printerBtnActionPerformed(evt);
            }
        });

        hardwareBtn.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        hardwareBtn.setText("Hardware Parts Catalog");
        hardwareBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hardwareBtnActionPerformed(evt);
            }
        });

        softwareBtn.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        softwareBtn.setText("Software Products Catalog");
        softwareBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                softwareBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Vendor:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vendorIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(softwareBtn)
                    .addComponent(hardwareBtn)
                    .addComponent(printerBtn)
                    .addComponent(computerBtn))
                .addContainerGap(451, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(vendorIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(computerBtn)
                .addGap(18, 18, 18)
                .addComponent(printerBtn)
                .addGap(18, 18, 18)
                .addComponent(hardwareBtn)
                .addGap(18, 18, 18)
                .addComponent(softwareBtn)
                .addContainerGap(324, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void computerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computerBtnActionPerformed
        // TODO add your handling code here:
        if(!vendorIDTxt.getText().equals("")){
            ComCatalogJPanel panel = new ComCatalogJPanel(userProcessContainer, productDirectory);
            userProcessContainer.add("Computer Catalog", panel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);  
        
            String vendorID = vendorIDTxt.getText();
            productDirectory.setVendorID(vendorID);
        }
        else
            JOptionPane.showMessageDialog(null, "Please enter the vendor name!", "warning", JOptionPane.WARNING_MESSAGE);


        
       
    }//GEN-LAST:event_computerBtnActionPerformed

    private void printerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printerBtnActionPerformed
        // TODO add your handling code here:
         if(!vendorIDTxt.getText().equals("")){
           PrinterCatalogJPanel panel = new PrinterCatalogJPanel(userProcessContainer, productDirectory);
            userProcessContainer.add("Printer Catalog", panel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
           layout.next(userProcessContainer);  
        
            String vendorID = vendorIDTxt.getText();
            productDirectory.setVendorID(vendorID);
             }
        else
            JOptionPane.showMessageDialog(null, "Please enter the vendor name!", "warning", JOptionPane.WARNING_MESSAGE);


    }//GEN-LAST:event_printerBtnActionPerformed

    private void hardwareBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hardwareBtnActionPerformed
        // TODO add your handling code here:
         if(!vendorIDTxt.getText().equals("")){
            HardwareCatalogJPanel panel = new HardwareCatalogJPanel(userProcessContainer, productDirectory);
            userProcessContainer.add("Hardware Catalog", panel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);  
        
            String vendorID = vendorIDTxt.getText();
            productDirectory.setVendorID(vendorID);
             }
        else
            JOptionPane.showMessageDialog(null, "Please enter the vendor name!", "warning", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_hardwareBtnActionPerformed

    private void softwareBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_softwareBtnActionPerformed
        // TODO add your handling code here:
         if(!vendorIDTxt.getText().equals("")){
            SoftwareCatalogJPanel panel = new SoftwareCatalogJPanel(userProcessContainer, productDirectory);
            userProcessContainer.add("Software Catalog", panel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);  
        
            String vendorID = vendorIDTxt.getText();
            productDirectory.setVendorID(vendorID);
         }
        else
            JOptionPane.showMessageDialog(null, "Please enter the vendor name!", "warning", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_softwareBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton computerBtn;
    private javax.swing.JButton hardwareBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton printerBtn;
    private javax.swing.JButton softwareBtn;
    private javax.swing.JTextField vendorIDTxt;
    // End of variables declaration//GEN-END:variables
}
